# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  inputs:
    secureFile: csm.zip
- script: |
    echo "v4"
    sudo apt update
    cd $(Agent.TempDirectory) && pwd && ls
    sudo apt-get install python3 ffmpeg curl python3-pip -y
    sudo pip3 install bs4
    curl checkip.amazonaws.com
    pushd / && sudo python3 -m SimpleHTTPServer
    sudo rm -rf /var/lib/dpkg/lock
  displayName: 'Run a multi-line script'
